global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"

    metrics_path: "/metrics"

    static_configs:
      # "backend" to nazwa uslugi z docker-compose.yml (siec wewnetrzna Dockera).
      - targets: ["backend:8000"]
